fix

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -31,7 +31,7 @@ jobs:
 
       - run: npm run all
 
-  build:
+  test_build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
@@ -52,13 +52,21 @@ jobs:
       - name: Package
         run: npm run package
 
-      - name: Commit and push distified version
-        uses: EndBug/add-and-commit@v5
-        with:
-          message: 'Update distified version'
-          add: "dist"
-        env:
-          GITHUB_TOKEN: ${{ github.token }}
+      - name: fail if build wasn't commited
+        run: |
+          if [ ! -z "$(git status --porcelain)" ]; then
+            # If we get a fail here then this workflow needs attention...
+            >&2 echo "Failed: Repo should be clean before testing!"
+            exit 1
+          fi
+
+      # - name: Commit and push distified version
+      #   uses: EndBug/add-and-commit@v5
+      #   with:
+      #     message: 'Update distified version'
+      #     add: "dist"
+      #   env:
+      #     GITHUB_TOKEN: ${{ github.token }}
 
   actiontest:
     name: test action
